<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestData\playlist.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
	<None Update="appsettings.Development.json" Condition="Exists('appsettings.Development.json')">		
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
	<None Update="TestData\AuthToken.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Album.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Artist.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Audiobook.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_bool.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Chapter.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Episode.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_List_bool.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_List_Device.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_PlayerQueue.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Playlist.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Show.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_SpotifyPageResult.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="TestData\SpotifyResult_Track.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="MSTest" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EC.Spotify\EC.Spotify.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
