@EC.Spotify.HostAddress = https://localhost:5001
@EC.Spotify.AlbumId = 7a7arAXDE0BiaMgHLhdjGF
@EC.Spotify.AlbumIds = 7a7arAXDE0BiaMgHLhdjGF,4aawyAB9vmqN3uQ7FjRGTy,1A2B3C4D5E6F7G8H9I0J1K



### album get
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}
Accept: application/json

### album tracks get all
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}/tracks
Accept: application/json

### album tracks get all (paged)
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}/tracks?offset=0&limit=20
Accept: application/json

### album get raw
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}/raw
Accept: application/json

### album tracks get all raw
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}/tracks/raw
Accept: application/json

### album tracks get all raw (paged)
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}/tracks/raw?offset=0&limit=20
Accept: application/json
