@EC.Spotify.HostAddress = https://localhost:5001

@EC.Spotify.AlbumId = 7a7arAXDE0BiaMgHLhdjGF
@EC.Spotify.ArtistId = 0X380XXQSNBYuleKzav5UO
@EC.Spotify.AudiobookId = 587ehiVcGuXjxKMECQneQ6
@EC.Spotify.ChapterId = 3OCSAZnatejMEd0Q5Ohlq7
@EC.Spotify.EpisodeId = 3UcmY44Vwv4Ldh0Jd1HZ4m
@EC.Spotify.ShowId = 2zBUqgc1ZmvqqEdP4g2jjA
@EC.Spotify.PlaylistId = 5qJY3DO0w0BqLmelaV2Vwq
@EC.Spotify.TrackId = 4tjcBY787A2ZkRJpPIsGIS



### album
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}
Accept: application/json

### album tracks
GET {{EC.Spotify.HostAddress}}/Albums/{{EC.Spotify.AlbumId}}/tracks
Accept: application/json



### artist
GET {{EC.Spotify.HostAddress}}/Artists/{{EC.Spotify.ArtistId}}
Accept: application/json

### artist albums
GET {{EC.Spotify.HostAddress}}/Artists/{{EC.Spotify.ArtistId}}/albums
Accept: application/json

### artist albums page
GET {{EC.Spotify.HostAddress}}/Artists/{{EC.Spotify.ArtistId}}/albums?offset=20&limit=20&albumTypes=album,single
Accept: application/json


### artist albums page
#  AlbumType
#    Album = 1,
#    Single =  2,
#    AppearsOn = 4,
#    Compilation = 8
GET {{EC.Spotify.HostAddress}}/Artists/{{EC.Spotify.ArtistId}}/albums?offset=20&limit=20&albumTypes=1,2
Accept: application/json



### audiobook
GET {{EC.Spotify.HostAddress}}/Audiobooks/{{EC.Spotify.AudiobookId}}
Accept: application/json

### audiobook chapters
GET {{EC.Spotify.HostAddress}}/Audiobooks/{{EC.Spotify.AudiobookId}}/chapters
Accept: application/json

### audiobook chapters page
GET {{EC.Spotify.HostAddress}}/Audiobooks/{{EC.Spotify.AudiobookId}}/chapters?offset=20&limit=20
Accept: application/json



### chapters
GET {{EC.Spotify.HostAddress}}/Chapters/{{EC.Spotify.ChapterId}}
Accept: application/json



### episodes
GET {{EC.Spotify.HostAddress}}/Episodes/{{EC.Spotify.EpisodeId}}
Accept: application/json



### library
#  LibraryType
#    Album = 0
#    Audiobook = 1
#    Episode = 2
#    Playlist = 3
#    Show = 4
#    Track = 5
#    User = 6

### library check
GET {{EC.Spotify.HostAddress}}/Library/check?id={{EC.Spotify.TrackId}}&type=5
Accept: application/json

### library check batch
GET {{EC.Spotify.HostAddress}}/Library/check/batch
Content-Type: application/json
Accept: application/json

[
  { "id": "{{EC.Spotify.TrackId}}", "type": 5 },
  { "id": "{{EC.Spotify.AlbumId}}", "type": 0 }
]

### library add
POST {{EC.Spotify.HostAddress}}/Library?id={{EC.Spotify.TrackId}}&type=5
Accept: application/json

### library add batch
POST {{EC.Spotify.HostAddress}}/Library/batch
Content-Type: application/json
Accept: application/json

[
  { "id": "{{EC.Spotify.TrackId}}", "type": 5 },
  { "id": "{{EC.Spotify.AlbumId}}", "type": 0 }
]

### library remove
DELETE {{EC.Spotify.HostAddress}}/Library?id={{EC.Spotify.TrackId}}&type=5
Accept: application/json

### library remove batch
DELETE {{EC.Spotify.HostAddress}}/Library/batch
Content-Type: application/json
Accept: application/json

[
  { "id": "{{EC.Spotify.TrackId}}", "type": 5 },
  { "id": "{{EC.Spotify.AlbumId}}", "type": 0 }
]



### player devices
GET {{EC.Spotify.HostAddress}}/Player/devices
Accept: application/json

### player transfer device
POST {{EC.Spotify.HostAddress}}/Player/transfer?deviceId=4aeeb14560726dd6f4a37bc6d5cf5e8be580e288&play=true
Accept: application/json

### player state
GET {{EC.Spotify.HostAddress}}/Player/state
Accept: application/json

### player currently playing
GET {{EC.Spotify.HostAddress}}/Player/currently-playing1
Accept: application/json

### player queue get
GET {{EC.Spotify.HostAddress}}/Player/queue
Accept: application/json

### player queue add
POST {{EC.Spotify.HostAddress}}/Player/queue?trackUri=spotify:track:{{EC.Spotify.TrackId}}
Accept: application/json

### player play
POST {{EC.Spotify.HostAddress}}/Player/play
Accept: application/json

### player pause
POST {{EC.Spotify.HostAddress}}/Player/pause
Accept: application/json

### player next
POST {{EC.Spotify.HostAddress}}/Player/next
Accept: application/json

### player previous
POST {{EC.Spotify.HostAddress}}/Player/previous
Accept: application/json

### player seek
POST {{EC.Spotify.HostAddress}}/Player/seek?positionMilliseconds=60000
Accept: application/json

### player volume
POST {{EC.Spotify.HostAddress}}/Player/volume?volume=100
Accept: application/json

### player repeat
#  playerRepeatMode
#    Off = 0
#    Track = 1
#    Context = 2
POST {{EC.Spotify.HostAddress}}/Player/repeat?playerRepeatMode=0
Accept: application/json

### player shuffle
#  playerShuffleMode
#    Off = 0
#    On = 1
POST {{EC.Spotify.HostAddress}}/Player/shuffle?playerShuffleMode=1
Accept: application/json



### playlist
#  ReferenceItemType
#    Album = 0
#    Audiobook = 1
#    Episode = 2
#    Playlist = 3
#    Show = 4
#    Track = 5
#    User = 6

### playlist get
GET {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}
Accept: application/json

### playlist items
GET {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items
Accept: application/json

### playlist items page
GET {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items?offset=20&limit=20
Accept: application/json

### playlist update
PUT {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}
Content-Type: application/json
Accept: application/json

{
  "name": "My Updated Playlist",
  "public": true,
  "collaborative": false,
  "description": "Updated playlist description"
}

### playlist item add
POST {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items
Content-Type: application/json
Accept: application/json

{ "id": "{{EC.Spotify.TrackId}}", "type": 5 }

### playlist item add with position
POST {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items?position=0
Content-Type: application/json
Accept: application/json

{ "id": "{{EC.Spotify.TrackId}}", "type": 5 }

### playlist item add batch
POST {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items/batch
Content-Type: application/json
Accept: application/json

[
  { "id": "{{EC.Spotify.TrackId}}", "type": 5 },
  { "id": "{{EC.Spotify.AlbumId}}", "type": 0 }
]

### playlist item remove
DELETE {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items
Content-Type: application/json
Accept: application/json

{ "id": "{{EC.Spotify.TrackId}}", "type": 5 }

### playlist item remove batch
DELETE {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/items/batch
Content-Type: application/json
Accept: application/json

[
  { "id": "{{EC.Spotify.TrackId}}", "type": 5 },
  { "id": "{{EC.Spotify.AlbumId}}", "type": 0 }
]

### playlist image add
PUT {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/image
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="image"; filename="playlist.jpg"
Content-Type: image/jpeg

< ./playlist.jpg
------Boundary--

### playlist image get
GET {{EC.Spotify.HostAddress}}/Playlist/{{EC.Spotify.PlaylistId}}/image



### search
#  SearchTypes
#    Album = 1
#    Artist = 2
#    Playlist = 4
#    Track = 8
#    Show = 16
#    Episode = 32
#    Audiobook = 64
#BITWISE: 1 + 2 = 3 (Album OR Artist)

### Album = 1
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "The Downward Spiral",
  "type": 1
}

### Artist = 2
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Nine Inch Nails",
  "type": 2
}

### Artist = 2 page
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Nine Inch Nails",
  "type": 2,
  "offset": 0,
  "limit": 10
}

### Playlist = 4
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Track 10",
  "type": 4
}

### Track = 8
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Reptile",
  "type": 8
}

### Show = 16
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Joe Rogan Experience",
  "type": 16
}

### Episode = 32
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Back",
  "type": 32
}

### Audiobook = 64
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Stephen King name:It",
  "type": 64
}

### Bitwise search = 8 + 2
POST {{EC.Spotify.HostAddress}}/Search
Content-Type: application/json
Accept: application/json

{
  "query": "Bohemian Rhapsody",
  "type": 10
}



### shows
GET {{EC.Spotify.HostAddress}}/Shows/{{EC.Spotify.ShowId}}
Accept: application/json

### shows
GET {{EC.Spotify.HostAddress}}/Shows/{{EC.Spotify.ShowId}}/Episodes
Accept: application/json



### track
GET {{EC.Spotify.HostAddress}}/Tracks/{{EC.Spotify.TrackId}}
Accept: application/json



### user
#  UserTopType
#    Artists = 1
#    Tracks = 2

#  UserTopTimeRange
#    LongTerm = 0
#    MediumTerm = 1
#    ShortTerm = 2

### user my albums
GET {{EC.Spotify.HostAddress}}/User/albums
Accept: application/json

### user my albums page
GET {{EC.Spotify.HostAddress}}/User/albums?offset=0&limit=20
Accept: application/json

### user my audiobooks
GET {{EC.Spotify.HostAddress}}/User/audiobooks
Accept: application/json

### user my audiobooks page
GET {{EC.Spotify.HostAddress}}/User/audiobooks?offset=0&limit=20
Accept: application/json

### user my episodes
GET {{EC.Spotify.HostAddress}}/User/episodes
Accept: application/json

### user my episodes page
GET {{EC.Spotify.HostAddress}}/User/episodes?offset=0&limit=20
Accept: application/json

### user my playlists
GET {{EC.Spotify.HostAddress}}/User/playlists
Accept: application/json

### user my playlists page
GET {{EC.Spotify.HostAddress}}/User/playlists?offset=0&limit=20
Accept: application/json

### user my shows
GET {{EC.Spotify.HostAddress}}/User/shows
Accept: application/json

### user my shows page
GET {{EC.Spotify.HostAddress}}/User/shows?offset=0&limit=20
Accept: application/json

### user my tracks
GET {{EC.Spotify.HostAddress}}/User/tracks
Accept: application/json

### user my tracks page
GET {{EC.Spotify.HostAddress}}/User/tracks?offset=0&limit=20
Accept: application/json

### user top artists (medium term)
GET {{EC.Spotify.HostAddress}}/User/top?userTopType=1&userTopTimeRange=1
Accept: application/json

### user top tracks (short term)
GET {{EC.Spotify.HostAddress}}/User/top?userTopType=2&userTopTimeRange=2
Accept: application/json

### user top tracks page (long term)
GET {{EC.Spotify.HostAddress}}/User/top?userTopType=2&userTopTimeRange=0&offset=0&limit=20
Accept: application/json
