name: Build And Test
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore src/EC.Spotify/EC.Spotify.Tests/EC.Spotify.Tests.csproj 
      - name: Build
        run: dotnet build src/EC.Spotify/EC.Spotify.Tests/EC.Spotify.Tests.csproj --no-restore
      - name: Run tests
        run: dotnet test src/EC.Spotify/EC.Spotify.Tests/EC.Spotify.Tests.csproj --no-build --verbosity normal
