name: Pack And Publish
on:
  release:
    types: [published]

jobs:
  pack-and-publish:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy file within repo
        run: |
          ls
          cp LICENSE.txt src/EC.Spotify/EC.Spotify/LICENSE.txt
          cp README.md src/EC.Spotify/EC.Spotify/README.md
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: dotnet pack
        run: |
          TAG_REF="${GITHUB_REF}"
          TAG_NAME=$(echo "${TAG_REF}" | cut -d '/' -f3)
          VERSION_NUMBER=$(echo "${TAG_NAME}" | sed 's/^v//')
          dotnet pack src/EC.Spotify/EC.Spotify/EC.Spotify.csproj -p:PackageVersion=${VERSION_NUMBER}
      - name: push to nuget
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push "**/*.snupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate