name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - .github/wiki/**
      - .github/workflows/PublishWiki.yml
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: ".github/wiki/"